apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 3  # 레플리카 수
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: gudev/boaz-k8s:v1
        ports:
        - containerPort: 8080